# ref: https://qiita.com/shin-ch13/items/9d207a70ccc8467f7bab
# ref: https://www.tohoho-web.com/ex/tmux.html

# Enable 256-color support in tmux
# https://www.reddit.com/r/vim/comments/5416d0/true_colors_in_vim_under_tmux/
set-option -g terminal-overrides ',xterm-256color:Tc'

# Remove ESC key delay
set-option -s escape-time 0

# Place the status bar at the top
set-option -g status-position top

# Set left/right status bar lengths
set-option -g status-left-length 90

# #P => pane index
# Show on the far left
set-option -g status-left '#H:[#P]'

# Wi-Fi, battery level, and current time
# Show on the far right
set-option -g status-right '#(wifi) #(battery --tmux) [%Y-%m-%d(%a) %H:%M]'

# Redraw the status bar every second
set-option -g status-interval 1

# Center the status (mainly window index)
set-option -g status-justify centre

# Set status bar colors
set-option -g status-bg "colour238"

# Set status line text color
set-option -g status-fg "colour255"

# Move between panes with vim keybindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes with vim keybindings
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Create a new window in the current directory
# ref: https://unix.stackexchange.com/a/118381
bind c new-window -c "#{pane_current_path}"

# Split pane vertically with |
bind | split-window -h -c "#{pane_current_path}"

# Split pane horizontally with -
bind - split-window -v -c "#{pane_current_path}"

# Change base index
set-option -g base-index 1

# Enable mouse mode
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

# Configure copy mode
# Use vim keybindings in copy mode
setw -g mode-keys vi

# Start selection with 'v'
bind -T copy-mode-vi v send -X begin-selection

# Select line with 'V'
bind -T copy-mode-vi V send -X select-line

# Start block selection with 'C-v'
bind -T copy-mode-vi C-v send -X rectangle-toggle

# Yank selection with 'y'
bind -T copy-mode-vi y send -X copy-selection

# Yank line with 'Y'
bind -T copy-mode-vi Y send -X copy-line

# Paste with 'C-p'
bind-key C-p paste-buffer

#===================================
# tpm - Tmux Plugin Manager
#===================================

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

#===================================
# Auto start tmux and restore
#===================================

# auto start terminal
set -g @continuum-boot 'on'
set -g @continuum-boot-options 'iterm'

# auto restore tmux
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager
# (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
