path=(
  "$HOME/.local/bin"
  "$HOME/.local/share/mise/shims"
  "/opt/homebrew/opt/rustup/bin"
  "$HOME/.bun/bin"
  "$HOME/.cargo/bin"
  "$HOME/.deno/bin"
  "$HOME/go/bin"
  "$HOME/development/flutter/bin"
  "$HOME/Library/pnpm"
  $path
)
